### ISSUE TITLE
Add LEDAcrypt

### ISSUE THREAD

**Issue by benj-zen** [cryptoeng/pqdb#109]

**Comment by TomerHawk** [comment]
How should I name the parameter sets? Does a comment fulfill the option for an user to divide between them?
Because in LEDAcrypt there are 3 sets which are equal from the parameters but not from the executive and security part. 
They divide in:
* LEDAdecoder executing two times the out-of-place iteration function 
* LEDAdecoder executing one time the in-place iteration function followed by one execution of the out-of-place iteration function
* LEDAdecoder executing two  times  the  in-place  iteration function

https://www.ledacrypt.org/documents/LEDAcrypt_v3.pdf#page=79, from page 79 to 81
