### ISSUE TITLE
Fix errors in broken branches

### ISSUE THREAD

**Issue by Hennich** [cryptoeng/pqdb#54]
Branches gemss, rainbow, mqdss and LUOV are broken.
Starting with gemss, find out why (some of the others still contain tabs, but that's not the only issue).
Tell me (Henning) what was wrong.

**Comment by dingens** [comment]
What do you mean by "broken", exactly?

I've now fixed the validation errors in the GeMSS branch. What I did was:
- merge from master
- fix errors in the scheme (error messages written down from memory, thus they are not correct by the letter):
  - must not have additional property `ct/msg` → this parameter has been renamed to `ct|sig`
  - `side channel guarding` must be an object → add information (see `schema/implementation.json`), or remove the whole entry
  - `number of operations` missing → add data (see `schema/paramset.json`)

I guess with the other schemes, the errors are similar. Can you try and fix them yourself using the instructions from above? If you encounter other problems, just ping me.

**Comment by dingens** [comment]
Also, I noted that the LUOV branch is based on the GeMSS branch. This makes things difficult (for example, because after `git co LUOV` you get errors within gemss) and it makes diffs between master and LUOV contain gemss changes.

I'd recommend you either a) create a new LUOV branch off from master where you cherry-pick the changes onto or b) wait until gemss is working and merged before you continue working on LUOV.

**Comment by benj-zen** [comment]
@Hennich I'd recommend that you continue working on the schemes using the enter-data-helper. This way you don't have to worry about creating valid .yaml files.

**Comment by Hennich** [comment]
New problem: Locally the check works, but on github it doesn't.

**Comment by benj-zen** [comment]
Seems like there was an issue with github that canceled the workflow runs. I restarted the jobs and now they all validated.

**Comment by benj-zen** [comment]
I will close this. Further discussion can take place in the PRs.
